FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build

# Install the dotnet-ef tool and update the PATH environment variable
RUN dotnet tool install --global dotnet-ef
ENV PATH="${PATH}:/root/.dotnet/tools"

# Set the working directory
WORKDIR /app

# Copy the csproj file and restore the dependencies
COPY *.csproj ./
RUN dotnet restore

# Copy the rest of the application code
COPY . ./

ENTRYPOINT ["dotnet", "ef", "database", "update"]
