replicaCount: 1

selector: "users-service"

container:
  name: "users-service"
  image: "idiordiev/online-shop-users-service"

service:
  ports:
    - name: http
      port: 80
      containerPort: 80

migrations:
  container:
    name: "run-migrations"
    image: "idiordiev/online-shop-users-service-migrations"
    tag: "latest"
    
ingress:
  path: "/api/users"
  port: "http"

postgresql:
  auth:
    database: "users"

rabbitmq:
  options:
    - name: "EntityExchange"
      value: "entity"
    - name: "EntityCreateQueue"
      value: "entity.create"
    - name: "EntityUpdateQueue"
      value: "entity.update"
    - name: "EntityDeleteQueue"
      value: "entity.delete"
    - name: "EmailExchange"
      value: "email"
    - name: "EmailSendQueue"
      value: "email.send"