replicaCount: 1

selector: "baskets-service"

container:
  name: "baskets-service"
  image: "idiordiev/online-shop-baskets-service"

service:
  ports:
    - name: http
      port: 80
      containerPort: 80

migrations:
  container:
    name: "run-migrations"
    image: "idiordiev/online-shop-baskets-service-migrations"
    tag: "latest"
    
ingress:
  path: "/api/baskets"
  port: "http"

postgresql:
  auth:
    database: "baskets"

rabbitmq:
  options:
    - name: "EntityExchange"
      value: "entity"
    - name: "EntityCreateQueue"
      value: "entity.create"
    - name: "EntityUpdateQueue"
      value: "entity.update"
    - name: "EntityDeleteQueue"
      value: "entity.delete"